---
- name: MongoDB | Create directory for mongodb backups
  file:
    state: directory
    path: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/mongodb"

- name: MongoDB | Backup mongo admin database
  command: "mongodump -d {{ backup_mongodb_admin_db }} --username=\"{{ backup_mongodb_backup_user }}\" --password=\"{{ backup_mongodb_backup_pass }}\" --out={{ backup_mongodb_backup_file_name }}"
  args:
    chdir: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/mongodb"

- name: MongoDB | Backup mongo database
  command: "mongodump -d {{ backup_mongodb_db }} --username=\"{{ backup_mongodb_user }}\" --password=\"{{ backup_mongodb_pass }}\" --out={{ backup_mongodb_backup_file_name }}"
  args:
    chdir: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/mongodb"

- name: MongoDB | Register backup file state
  stat:
    path: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/mongodb/{{ backup_mongodb_backup_file_name }}"
  register: backup_state

- name: MongoDB | Fail when backup was not created
  fail:
    msg: "Backup file was not created"
  when: backup_state.stat.exists == false
