---
- name: MySQL | Create directory for mysql backups
  file:
    state: directory
    path: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/mysql"

- name: MySQL | Backup mysql database
  shell: "mysqldump {{ backup_mysql_db }} --user=\"{{ backup_mysql_user }}\" --password=\"{{ backup_mysql_pass }}\" --result-file={{ backup_mysql_backup_file_name }}"
  args:
    chdir: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/mysql"
    creates: "{{ backup_mysql_backup_file_name }}"

- name: MySQL | Register backup file state
  stat:
    path: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/mysql/{{ backup_mysql_backup_file_name }}"
  register: backup_state

- name: MySQL | Fail when backup was not created
  fail:
    msg: "Backup file was not created"
  when: backup_state.stat.exists == false