---
- name: Redis | Create directory for redis backups
  file:
    state: directory
    path: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/redis"

- name: Redis | Copy redis dump to backup tmp folder
  shell: "cp {{ backup_redis_save_path }}/dump.rdb {{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/redis/"

- name: Redis | Register backup file state
  stat:
    path: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/redis/dump.rdb"
  register: backup_state

- name: Redis | Fail when backup was not created
  fail:
    msg: "Backup file was not created"
  when: backup_state.stat.exists == false