---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
  - name: Register timestamp variable
    command: date +%Y_%m_%d_%H_%M_%S
    register: timestamp
  roles:
    - role: ansible-role-backup
